//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Words.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Words.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorschaugröße: ähnelt.
        /// </summary>
        public static string cbPreviewSize {
            get {
                return ResourceManager.GetString("cbPreviewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hintergrund wählen ähnelt.
        /// </summary>
        public static string cbTitle {
            get {
                return ResourceManager.GetString("cbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einzelne Farbe verwenden ähnelt.
        /// </summary>
        public static string cbUseSingleColor {
            get {
                return ResourceManager.GetString("cbUseSingleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abbrechen ähnelt.
        /// </summary>
        public static string dialogCancel {
            get {
                return ResourceManager.GetString("dialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Schließen ähnelt.
        /// </summary>
        public static string dialogClose {
            get {
                return ResourceManager.GetString("dialogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string dialogOK {
            get {
                return ResourceManager.GetString("dialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hinzufügen ähnelt.
        /// </summary>
        public static string paAdd {
            get {
                return ResourceManager.GetString("paAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vollbild ähnelt.
        /// </summary>
        public static string paFullscreen {
            get {
                return ResourceManager.GetString("paFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor: ähnelt.
        /// </summary>
        public static string paMonitor {
            get {
                return ResourceManager.GetString("paMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nach unten ähnelt.
        /// </summary>
        public static string paMoveDown {
            get {
                return ResourceManager.GetString("paMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Nach oben ähnelt.
        /// </summary>
        public static string paMoveUp {
            get {
                return ResourceManager.GetString("paMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Es muss mindestens eine Einstellung gültig sein (ohne rote Markierung). ähnelt.
        /// </summary>
        public static string paMsgValidOption {
            get {
                return ResourceManager.GetString("paMsgValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position (von links/oben): ähnelt.
        /// </summary>
        public static string paPosition {
            get {
                return ResourceManager.GetString("paPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position: {0}/{1}, Größe: {2}x{3} ähnelt.
        /// </summary>
        public static string paPositionSize {
            get {
                return ResourceManager.GetString("paPositionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primär ähnelt.
        /// </summary>
        public static string paPrimary {
            get {
                return ResourceManager.GetString("paPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktualisieren ähnelt.
        /// </summary>
        public static string paRefresh {
            get {
                return ResourceManager.GetString("paRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entfernen ähnelt.
        /// </summary>
        public static string paRemove {
            get {
                return ResourceManager.GetString("paRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sekundär ähnelt.
        /// </summary>
        public static string paSecondary {
            get {
                return ResourceManager.GetString("paSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sekundär/Extern ähnelt.
        /// </summary>
        public static string paSecondaryExternal {
            get {
                return ResourceManager.GetString("paSecondaryExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Größe (Breite/Höhe): ähnelt.
        /// </summary>
        public static string paSize {
            get {
                return ResourceManager.GetString("paSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Präsentationsbereich festlegen ähnelt.
        /// </summary>
        public static string paTitle {
            get {
                return ResourceManager.GetString("paTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lied hinzufügen ähnelt.
        /// </summary>
        public static string slAddSong {
            get {
                return ResourceManager.GetString("slAddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweitert ähnelt.
        /// </summary>
        public static string slAdvanced {
            get {
                return ResourceManager.GetString("slAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright: ähnelt.
        /// </summary>
        public static string slCopyright {
            get {
                return ResourceManager.GetString("slCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fertig ({0:d}) ähnelt.
        /// </summary>
        public static string slFinishedLoadingN {
            get {
                return ResourceManager.GetString("slFinishedLoadingN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright ähnelt.
        /// </summary>
        public static string slGridCopyright {
            get {
                return ResourceManager.GetString("slGridCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sprache ähnelt.
        /// </summary>
        public static string slGridLanguage {
            get {
                return ResourceManager.GetString("slGridLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quelle ähnelt.
        /// </summary>
        public static string slGridSource {
            get {
                return ResourceManager.GetString("slGridSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Titel ähnelt.
        /// </summary>
        public static string slGridTitle {
            get {
                return ResourceManager.GetString("slGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade ... ähnelt.
        /// </summary>
        public static string slLoading {
            get {
                return ResourceManager.GetString("slLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lade ({0:d}) ... ähnelt.
        /// </summary>
        public static string slLoadingN {
            get {
                return ResourceManager.GetString("slLoadingN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen ähnelt.
        /// </summary>
        public static string slSearch {
            get {
                return ResourceManager.GetString("slSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Suchen ähnelt.
        /// </summary>
        public static string slSearchButton {
            get {
                return ResourceManager.GetString("slSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liedtext auch durchsuchen ähnelt.
        /// </summary>
        public static string slSearchInText {
            get {
                return ResourceManager.GetString("slSearchInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liederbuch: ähnelt.
        /// </summary>
        public static string slSongbook {
            get {
                return ResourceManager.GetString("slSongbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liednummer: ähnelt.
        /// </summary>
        public static string slSongnumber {
            get {
                return ResourceManager.GetString("slSongnumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liederliste ähnelt.
        /// </summary>
        public static string slTitle {
            get {
                return ResourceManager.GetString("slTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das Verzeichnis für Lieder oder Hintergründe existiert nicht. Bitte ein anderes Verzeichnis wählen oder das Verzeichnis erstellen. ähnelt.
        /// </summary>
        public static string sMsgDirectoryMissing {
            get {
                return ResourceManager.GetString("sMsgDirectoryMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alle Dateien ähnelt.
        /// </summary>
        public static string vFilterAllFiles {
            get {
                return ResourceManager.GetString("vFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unterstützte Medientypen ähnelt.
        /// </summary>
        public static string vFilterSupportedMediaTypes {
            get {
                return ResourceManager.GetString("vFilterSupportedMediaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Aktive Präsentation ähnelt.
        /// </summary>
        public static string vMenuActivePresentation {
            get {
                return ResourceManager.GetString("vMenuActivePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medien hinzufügen ähnelt.
        /// </summary>
        public static string vMenuAddMedia {
            get {
                return ResourceManager.GetString("vMenuAddMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzeige schwarz schalten ähnelt.
        /// </summary>
        public static string vMenuBlackscreen {
            get {
                return ResourceManager.GetString("vMenuBlackscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Präsentationsbereich festlegen ähnelt.
        /// </summary>
        public static string vMenuChoosePresentationArea {
            get {
                return ResourceManager.GetString("vMenuChoosePresentationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Beenden ähnelt.
        /// </summary>
        public static string vMenuExit {
            get {
                return ResourceManager.GetString("vMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Datei ähnelt.
        /// </summary>
        public static string vMenuFile {
            get {
                return ResourceManager.GetString("vMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Präsentation ausblenden ähnelt.
        /// </summary>
        public static string vMenuHidePresentation {
            get {
                return ResourceManager.GetString("vMenuHidePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Medien ähnelt.
        /// </summary>
        public static string vMenuMedia {
            get {
                return ResourceManager.GetString("vMenuMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Neues Portfolio ähnelt.
        /// </summary>
        public static string vMenuNewPortfolio {
            get {
                return ResourceManager.GetString("vMenuNewPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portfolio ö_ffnen ähnelt.
        /// </summary>
        public static string vMenuOpenPortfolio {
            get {
                return ResourceManager.GetString("vMenuOpenPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Projektion ähnelt.
        /// </summary>
        public static string vMenuProjection {
            get {
                return ResourceManager.GetString("vMenuProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neu laden ähnelt.
        /// </summary>
        public static string vMenuRefresh {
            get {
                return ResourceManager.GetString("vMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portfolio _speichern ähnelt.
        /// </summary>
        public static string vMenuSavePortfolio {
            get {
                return ResourceManager.GetString("vMenuSavePortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portfolio speichern _unter ... ähnelt.
        /// </summary>
        public static string vMenuSavePortfolioAs {
            get {
                return ResourceManager.GetString("vMenuSavePortfolioAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einstellungen ähnelt.
        /// </summary>
        public static string vMenuSettings {
            get {
                return ResourceManager.GetString("vMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liedakkorde anzeigen ähnelt.
        /// </summary>
        public static string vMenuShowChords {
            get {
                return ResourceManager.GetString("vMenuShowChords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Präsentation anzeigen ähnelt.
        /// </summary>
        public static string vMenuShowPresentation {
            get {
                return ResourceManager.GetString("vMenuShowPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Liederliste anzeigen ähnelt.
        /// </summary>
        public static string vMenuShowSonglist {
            get {
                return ResourceManager.GetString("vMenuShowSonglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liedtext und Übersetzung tauschen ähnelt.
        /// </summary>
        public static string vMenuSwapTextAndTranslation {
            get {
                return ResourceManager.GetString("vMenuSwapTextAndTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einen Hintergrund für alle Lieder verwenden ähnelt.
        /// </summary>
        public static string vMenuUsePortfolioBackground {
            get {
                return ResourceManager.GetString("vMenuUsePortfolioBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Das aktuelle Portfolio enthält möglicherweise ungespeicherte Änderungen. Wollen Sie es speichern? ähnelt.
        /// </summary>
        public static string vMsgSavePortfolioChanges {
            get {
                return ResourceManager.GetString("vMsgSavePortfolioChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Änderungen speichern? ähnelt.
        /// </summary>
        public static string vMsgSavePortfolioChangesTitle {
            get {
                return ResourceManager.GetString("vMsgSavePortfolioChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portfolio konnte nicht geladen werden. ähnelt.
        /// </summary>
        public static string vMsgUnableToLoadPortfolio {
            get {
                return ResourceManager.GetString("vMsgUnableToLoadPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Keine Vorschau verfügbar ähnelt.
        /// </summary>
        public static string vNoPreviewAvailable {
            get {
                return ResourceManager.GetString("vNoPreviewAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reihenfolge ähnelt.
        /// </summary>
        public static string vPanelOrder {
            get {
                return ResourceManager.GetString("vPanelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vorschau ähnelt.
        /// </summary>
        public static string vPanelPreview {
            get {
                return ResourceManager.GetString("vPanelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unbenanntes Portfolio ähnelt.
        /// </summary>
        public static string vTitleUnnamedPortfolio {
            get {
                return ResourceManager.GetString("vTitleUnnamedPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anzeige schwarz schalten ähnelt.
        /// </summary>
        public static string vToolbarBlackscreen {
            get {
                return ResourceManager.GetString("vToolbarBlackscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Aktives Lied im Editor bearbeiten ähnelt.
        /// </summary>
        public static string vToolbarEditActiveSong {
            get {
                return ResourceManager.GetString("vToolbarEditActiveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Präsentation ausblenden (Desktop anzeigen) ähnelt.
        /// </summary>
        public static string vToolbarHidePresentation {
            get {
                return ResourceManager.GetString("vToolbarHidePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Neues Portfolio ähnelt.
        /// </summary>
        public static string vToolbarNewPortfolio {
            get {
                return ResourceManager.GetString("vToolbarNewPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portfolio öffnen ähnelt.
        /// </summary>
        public static string vToolbarOpenPortfolio {
            get {
                return ResourceManager.GetString("vToolbarOpenPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Portfolio speichern ähnelt.
        /// </summary>
        public static string vToolbarSavePortfolio {
            get {
                return ResourceManager.GetString("vToolbarSavePortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liedakkorde bei der Präsentation anzeigen ähnelt.
        /// </summary>
        public static string vToolbarShowChords {
            get {
                return ResourceManager.GetString("vToolbarShowChords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Editorfenster anzeigen ähnelt.
        /// </summary>
        public static string vToolbarShowEditorWindow {
            get {
                return ResourceManager.GetString("vToolbarShowEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Präsentation anzeigen ähnelt.
        /// </summary>
        public static string vToolbarShowPresentation {
            get {
                return ResourceManager.GetString("vToolbarShowPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liederliste anzeigen ähnelt.
        /// </summary>
        public static string vToolbarShowSonglist {
            get {
                return ResourceManager.GetString("vToolbarShowSonglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Einen Hintergrund für alle Lieder verwenden ähnelt.
        /// </summary>
        public static string vToolbarUsePortfolioBackground {
            get {
                return ResourceManager.GetString("vToolbarUsePortfolioBackground", resourceCulture);
            }
        }
    }
}
