//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsLive.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowTop {
            get {
                return ((int)(this["MainWindowTop"]));
            }
            set {
                this["MainWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MainWindowLeft {
            get {
                return ((int)(this["MainWindowLeft"]));
            }
            set {
                this["MainWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("620")]
        public int MainWindowWidth {
            get {
                return ((int)(this["MainWindowWidth"]));
            }
            set {
                this["MainWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("530")]
        public int MainWindowHeight {
            get {
                return ((int)(this["MainWindowHeight"]));
            }
            set {
                this["MainWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState MainWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["MainWindowState"]));
            }
            set {
                this["MainWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditorWindowTop {
            get {
                return ((int)(this["EditorWindowTop"]));
            }
            set {
                this["EditorWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EditorWindowLeft {
            get {
                return ((int)(this["EditorWindowLeft"]));
            }
            set {
                this["EditorWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("700")]
        public int EditorWindowWidth {
            get {
                return ((int)(this["EditorWindowWidth"]));
            }
            set {
                this["EditorWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int EditorWindowHeight {
            get {
                return ((int)(this["EditorWindowHeight"]));
            }
            set {
                this["EditorWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState EditorWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["EditorWindowState"]));
            }
            set {
                this["EditorWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SongListWindowTop {
            get {
                return ((int)(this["SongListWindowTop"]));
            }
            set {
                this["SongListWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SongListWindowLeft {
            get {
                return ((int)(this["SongListWindowLeft"]));
            }
            set {
                this["SongListWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int SongListWindowWidth {
            get {
                return ((int)(this["SongListWindowWidth"]));
            }
            set {
                this["SongListWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int SongListWindowHeight {
            get {
                return ((int)(this["SongListWindowHeight"]));
            }
            set {
                this["SongListWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState SongListWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["SongListWindowState"]));
            }
            set {
                this["SongListWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SongListSearchInText {
            get {
                return ((bool)(this["SongListSearchInText"]));
            }
            set {
                this["SongListSearchInText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SongListSearchExpanded {
            get {
                return ((bool)(this["SongListSearchExpanded"]));
            }
            set {
                this["SongListSearchExpanded"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SongsDirectory {
            get {
                return ((string)(this["SongsDirectory"]));
            }
            set {
                this["SongsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BackgroundsDirectory {
            get {
                return ((string)(this["BackgroundsDirectory"]));
            }
            set {
                this["BackgroundsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChooseBackgroundWindowTop {
            get {
                return ((int)(this["ChooseBackgroundWindowTop"]));
            }
            set {
                this["ChooseBackgroundWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ChooseBackgroundWindowLeft {
            get {
                return ((int)(this["ChooseBackgroundWindowLeft"]));
            }
            set {
                this["ChooseBackgroundWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int ChooseBackgroundWindowWidth {
            get {
                return ((int)(this["ChooseBackgroundWindowWidth"]));
            }
            set {
                this["ChooseBackgroundWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("450")]
        public int ChooseBackgroundWindowHeight {
            get {
                return ((int)(this["ChooseBackgroundWindowHeight"]));
            }
            set {
                this["ChooseBackgroundWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Normal")]
        public global::System.Windows.WindowState ChooseBackgroundWindowState {
            get {
                return ((global::System.Windows.WindowState)(this["ChooseBackgroundWindowState"]));
            }
            set {
                this["ChooseBackgroundWindowState"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int ChooseBackgroundPreviewWidth {
            get {
                return ((int)(this["ChooseBackgroundPreviewWidth"]));
            }
            set {
                this["ChooseBackgroundPreviewWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int PresentationTransition {
            get {
                return ((int)(this["PresentationTransition"]));
            }
            set {
                this["PresentationTransition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>1,True,0,0,0,0</string>\r\n  <string>0,False,0,0,800,600</string>\r\n</ArrayOf" +
            "String>")]
        public global::System.Collections.Specialized.StringCollection PresentationAreas {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PresentationAreas"]));
            }
            set {
                this["PresentationAreas"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SongTemplateFile {
            get {
                return ((string)(this["SongTemplateFile"]));
            }
            set {
                this["SongTemplateFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public int SongSlideTransition {
            get {
                return ((int)(this["SongSlideTransition"]));
            }
            set {
                this["SongSlideTransition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SongPresentationShowChords {
            get {
                return ((bool)(this["SongPresentationShowChords"]));
            }
            set {
                this["SongPresentationShowChords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EditorEnableSpellCheck {
            get {
                return ((bool)(this["EditorEnableSpellCheck"]));
            }
            set {
                this["EditorEnableSpellCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stop")]
        public global::WordsLive.Images.FinishAction ImagesFinishAction {
            get {
                return ((global::WordsLive.Images.FinishAction)(this["ImagesFinishAction"]));
            }
            set {
                this["ImagesFinishAction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ImagesEnableAutoAdvance {
            get {
                return ((bool)(this["ImagesEnableAutoAdvance"]));
            }
            set {
                this["ImagesEnableAutoAdvance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public uint ImagesAutoAdvanceSeconds {
            get {
                return ((uint)(this["ImagesAutoAdvanceSeconds"]));
            }
            set {
                this["ImagesAutoAdvanceSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500")]
        public int ImageTransition {
            get {
                return ((int)(this["ImageTransition"]));
            }
            set {
                this["ImageTransition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::WordsLive.PluginSettingsDictionary PluginSettings {
            get {
                return ((global::WordsLive.PluginSettingsDictionary)(this["PluginSettings"]));
            }
            set {
                this["PluginSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TemplateMasterEnable {
            get {
                return ((bool)(this["TemplateMasterEnable"]));
            }
            set {
                this["TemplateMasterEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TemplateMasterOverrideTextFormatting {
            get {
                return ((bool)(this["TemplateMasterOverrideTextFormatting"]));
            }
            set {
                this["TemplateMasterOverrideTextFormatting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TemplateMasterOverrideTextPosition {
            get {
                return ((bool)(this["TemplateMasterOverrideTextPosition"]));
            }
            set {
                this["TemplateMasterOverrideTextPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TemplateMasterOverrideSourceFormatting {
            get {
                return ((bool)(this["TemplateMasterOverrideSourceFormatting"]));
            }
            set {
                this["TemplateMasterOverrideSourceFormatting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TemplateMasterOverrideSourcePosition {
            get {
                return ((bool)(this["TemplateMasterOverrideSourcePosition"]));
            }
            set {
                this["TemplateMasterOverrideSourcePosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TemplateMasterOverrideCopyrightFormatting {
            get {
                return ((bool)(this["TemplateMasterOverrideCopyrightFormatting"]));
            }
            set {
                this["TemplateMasterOverrideCopyrightFormatting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TemplateMasterOverrideCopyrightPosition {
            get {
                return ((bool)(this["TemplateMasterOverrideCopyrightPosition"]));
            }
            set {
                this["TemplateMasterOverrideCopyrightPosition"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool TemplateMasterOverrideOutlineShadow {
            get {
                return ((bool)(this["TemplateMasterOverrideOutlineShadow"]));
            }
            set {
                this["TemplateMasterOverrideOutlineShadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PresentationAreaSettingsWindowLeft {
            get {
                return ((int)(this["PresentationAreaSettingsWindowLeft"]));
            }
            set {
                this["PresentationAreaSettingsWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PresentationAreaSettingsWindowTop {
            get {
                return ((int)(this["PresentationAreaSettingsWindowTop"]));
            }
            set {
                this["PresentationAreaSettingsWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("375")]
        public int PresentationAreaSettingsWindowWidth {
            get {
                return ((int)(this["PresentationAreaSettingsWindowWidth"]));
            }
            set {
                this["PresentationAreaSettingsWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("375")]
        public int PresentationAreaSettingsWindowHeight {
            get {
                return ((int)(this["PresentationAreaSettingsWindowHeight"]));
            }
            set {
                this["PresentationAreaSettingsWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseVlc {
            get {
                return ((bool)(this["UseVlc"]));
            }
            set {
                this["UseVlc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationVersion {
            get {
                return ((string)(this["ApplicationVersion"]));
            }
            set {
                this["ApplicationVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NoUpdateVersion {
            get {
                return ((string)(this["NoUpdateVersion"]));
            }
            set {
                this["NoUpdateVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastPortfolioDirectory {
            get {
                return ((string)(this["LastPortfolioDirectory"]));
            }
            set {
                this["LastPortfolioDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMediaDirectory {
            get {
                return ((string)(this["LastMediaDirectory"]));
            }
            set {
                this["LastMediaDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastSongDirectory {
            get {
                return ((string)(this["LastSongDirectory"]));
            }
            set {
                this["LastSongDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EditorShowOrderSlidesContent {
            get {
                return ((bool)(this["EditorShowOrderSlidesContent"]));
            }
            set {
                this["EditorShowOrderSlidesContent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreferPowerpointViewerToPowerpoint {
            get {
                return ((bool)(this["PreferPowerpointViewerToPowerpoint"]));
            }
            set {
                this["PreferPowerpointViewerToPowerpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PreferPowerpointForOdp {
            get {
                return ((bool)(this["PreferPowerpointForOdp"]));
            }
            set {
                this["PreferPowerpointForOdp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public uint SlideshowAutoAdvanceSeconds {
            get {
                return ((uint)(this["SlideshowAutoAdvanceSeconds"]));
            }
            set {
                this["SlideshowAutoAdvanceSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("350")]
        public int DocumentPageTransition {
            get {
                return ((int)(this["DocumentPageTransition"]));
            }
            set {
                this["DocumentPageTransition"] = value;
            }
        }
    }
}
