//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsLive.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordsLive.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loop.
        /// </summary>
        public static string avCheckboxLoop {
            get {
                return ResourceManager.GetString("avCheckboxLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset offset:.
        /// </summary>
        public static string avLabelResetOffset {
            get {
                return ResourceManager.GetString("avLabelResetOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use current position as:.
        /// </summary>
        public static string avLabelSetOffset {
            get {
                return ResourceManager.GetString("avLabelSetOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volume:.
        /// </summary>
        public static string avLabelVolume {
            get {
                return ResourceManager.GetString("avLabelVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string avOffsetEnd {
            get {
                return ResourceManager.GetString("avOffsetEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string avOffsetStart {
            get {
                return ResourceManager.GetString("avOffsetStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        public static string avTooltipPause {
            get {
                return ResourceManager.GetString("avTooltipPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        public static string avTooltipPlay {
            get {
                return ResourceManager.GetString("avTooltipPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string avTooltipStop {
            get {
                return ResourceManager.GetString("avTooltipStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply this background to all slides.
        /// </summary>
        public static string cbApplyToAllSlides {
            get {
                return ResourceManager.GetString("cbApplyToAllSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No image has been selected..
        /// </summary>
        public static string cbMsgErrNoImageSelected {
            get {
                return ResourceManager.GetString("cbMsgErrNoImageSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The background currently in use for this song was not found and is replaced by a black background..
        /// </summary>
        public static string cbMsgNotFound {
            get {
                return ResourceManager.GetString("cbMsgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background not found.
        /// </summary>
        public static string cbMsgNotFoundTitle {
            get {
                return ResourceManager.GetString("cbMsgNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option to select a background image is currently disabled, because the check box &apos;Use single color&apos; in the top left corner of this window is enabled. Please uncheck that option to select an image..
        /// </summary>
        public static string cbMsgWarnTrySelectImage {
            get {
                return ResourceManager.GetString("cbMsgWarnTrySelectImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background image selection disabled.
        /// </summary>
        public static string cbMsgWarnTrySelectImageTitle {
            get {
                return ResourceManager.GetString("cbMsgWarnTrySelectImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview size:.
        /// </summary>
        public static string cbPreviewSize {
            get {
                return ResourceManager.GetString("cbPreviewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backgrounds.
        /// </summary>
        public static string cbRootNode {
            get {
                return ResourceManager.GetString("cbRootNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose background.
        /// </summary>
        public static string cbTitle {
            get {
                return ResourceManager.GetString("cbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use single color.
        /// </summary>
        public static string cbUseSingleColor {
            get {
                return ResourceManager.GetString("cbUseSingleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string cfTooltipBold {
            get {
                return ResourceManager.GetString("cfTooltipBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string cfTooltipFont {
            get {
                return ResourceManager.GetString("cfTooltipFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        public static string cfTooltipFontColor {
            get {
                return ResourceManager.GetString("cfTooltipFontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font Size.
        /// </summary>
        public static string cfTooltipFontSize {
            get {
                return ResourceManager.GetString("cfTooltipFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string cfTooltipItalic {
            get {
                return ResourceManager.GetString("cfTooltipItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string cfTooltipOutline {
            get {
                return ResourceManager.GetString("cfTooltipOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow.
        /// </summary>
        public static string cfTooltipShadow {
            get {
                return ResourceManager.GetString("cfTooltipShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abort.
        /// </summary>
        public static string dialogAbort {
            get {
                return ResourceManager.GetString("dialogAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string dialogCancel {
            get {
                return ResourceManager.GetString("dialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string dialogClose {
            get {
                return ResourceManager.GetString("dialogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string dialogError {
            get {
                return ResourceManager.GetString("dialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore.
        /// </summary>
        public static string dialogIgnore {
            get {
                return ResourceManager.GetString("dialogIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string dialogOK {
            get {
                return ResourceManager.GetString("dialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string dialogRefresh {
            get {
                return ResourceManager.GetString("dialogRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page.
        /// </summary>
        public static string docCurrentPage {
            get {
                return ResourceManager.GetString("docCurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next page.
        /// </summary>
        public static string docNextPage {
            get {
                return ResourceManager.GetString("docNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page scale.
        /// </summary>
        public static string docPageScale {
            get {
                return ResourceManager.GetString("docPageScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous page.
        /// </summary>
        public static string docPreviousPage {
            get {
                return ResourceManager.GetString("docPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit to width.
        /// </summary>
        public static string docScaleFitToWidth {
            get {
                return ResourceManager.GetString("docScaleFitToWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole page.
        /// </summary>
        public static string docScaleWholePage {
            get {
                return ResourceManager.GetString("docScaleWholePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in editor.
        /// </summary>
        public static string eCommandOpenInEditor {
            get {
                return ResourceManager.GetString("eCommandOpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add slide/part.
        /// </summary>
        public static string eGridAddElementButton {
            get {
                return ResourceManager.GetString("eGridAddElementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCLI Song Number:.
        /// </summary>
        public static string eGridCcliSongNumberLabel {
            get {
                return ResourceManager.GetString("eGridCcliSongNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View song in SongSelect.
        /// </summary>
        public static string eGridCcliViewInSongSelect {
            get {
                return ResourceManager.GetString("eGridCcliViewInSongSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add part.
        /// </summary>
        public static string eGridContextAddPart {
            get {
                return ResourceManager.GetString("eGridContextAddPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add slide.
        /// </summary>
        public static string eGridContextAddSlide {
            get {
                return ResourceManager.GetString("eGridContextAddSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate slide.
        /// </summary>
        public static string eGridContextDuplicateSlide {
            get {
                return ResourceManager.GetString("eGridContextDuplicateSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove part.
        /// </summary>
        public static string eGridContextRemovePart {
            get {
                return ResourceManager.GetString("eGridContextRemovePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove slide.
        /// </summary>
        public static string eGridContextRemoveSlide {
            get {
                return ResourceManager.GetString("eGridContextRemoveSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string eGridContextRename {
            get {
                return ResourceManager.GetString("eGridContextRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename song.
        /// </summary>
        public static string eGridContextRenameSong {
            get {
                return ResourceManager.GetString("eGridContextRenameSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap text and translation.
        /// </summary>
        public static string eGridContextSwapTextAndTranslation {
            get {
                return ResourceManager.GetString("eGridContextSwapTextAndTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English;German;Spanish.
        /// </summary>
        public static string eGridLanguages {
            get {
                return ResourceManager.GetString("eGridLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text:.
        /// </summary>
        public static string eGridLanguageText {
            get {
                return ResourceManager.GetString("eGridLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation:.
        /// </summary>
        public static string eGridLanguageTranslation {
            get {
                return ResourceManager.GetString("eGridLanguageTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add selected part to order.
        /// </summary>
        public static string eGridOrderAddButton {
            get {
                return ResourceManager.GetString("eGridOrderAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string eGridOrderHeader {
            get {
                return ResourceManager.GetString("eGridOrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move part down.
        /// </summary>
        public static string eGridOrderMoveDownButton {
            get {
                return ResourceManager.GetString("eGridOrderMoveDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move part up.
        /// </summary>
        public static string eGridOrderMoveUpButton {
            get {
                return ResourceManager.GetString("eGridOrderMoveUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove part from order.
        /// </summary>
        public static string eGridOrderRemoveButton {
            get {
                return ResourceManager.GetString("eGridOrderRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show slides.
        /// </summary>
        public static string eGridOrderShowSlidesCheckbox {
            get {
                return ResourceManager.GetString("eGridOrderShowSlidesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        public static string eGridPartsHeader {
            get {
                return ResourceManager.GetString("eGridPartsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string eGridPreviewHeader {
            get {
                return ResourceManager.GetString("eGridPreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide.
        /// </summary>
        public static string eGridSlideTitle {
            get {
                return ResourceManager.GetString("eGridSlideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add another source.
        /// </summary>
        public static string eGridSourceAddNew {
            get {
                return ResourceManager.GetString("eGridSourceAddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string eGridSourceNumberLabel {
            get {
                return ResourceManager.GetString("eGridSourceNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songbook:.
        /// </summary>
        public static string eGridSourceSongbookLabel {
            get {
                return ResourceManager.GetString("eGridSourceSongbookLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spell check.
        /// </summary>
        public static string eGridSpellCheckCheckbox {
            get {
                return ResourceManager.GetString("eGridSpellCheckCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string eGridTextHeader {
            get {
                return ResourceManager.GetString("eGridTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string eGridTranslation {
            get {
                return ResourceManager.GetString("eGridTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add song to current portfolio.
        /// </summary>
        public static string eMenuAddToPortfolio {
            get {
                return ResourceManager.GetString("eMenuAddToPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change background for selected element.
        /// </summary>
        public static string eMenuChangeBackground {
            get {
                return ResourceManager.GetString("eMenuChangeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close song.
        /// </summary>
        public static string eMenuCloseSong {
            get {
                return ResourceManager.GetString("eMenuCloseSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string eMenuEdit {
            get {
                return ResourceManager.GetString("eMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit chords.
        /// </summary>
        public static string eMenuEditChords {
            get {
                return ResourceManager.GetString("eMenuEditChords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export song.
        /// </summary>
        public static string eMenuExportSong {
            get {
                return ResourceManager.GetString("eMenuExportSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string eMenuFile {
            get {
                return ResourceManager.GetString("eMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format song.
        /// </summary>
        public static string eMenuFormatSong {
            get {
                return ResourceManager.GetString("eMenuFormatSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import SongSelect song from Clipboard.
        /// </summary>
        public static string eMenuImportFromClipboard {
            get {
                return ResourceManager.GetString("eMenuImportFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New song.
        /// </summary>
        public static string eMenuNewSong {
            get {
                return ResourceManager.GetString("eMenuNewSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open song.
        /// </summary>
        public static string eMenuOpenSong {
            get {
                return ResourceManager.GetString("eMenuOpenSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Redo.
        /// </summary>
        public static string eMenuRedo {
            get {
                return ResourceManager.GetString("eMenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save song.
        /// </summary>
        public static string eMenuSaveSong {
            get {
                return ResourceManager.GetString("eMenuSaveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save song as.
        /// </summary>
        public static string eMenuSaveSongAs {
            get {
                return ResourceManager.GetString("eMenuSaveSongAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show presenter window.
        /// </summary>
        public static string eMenuShowPresenter {
            get {
                return ResourceManager.GetString("eMenuShowPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Split text at cursor position.
        /// </summary>
        public static string eMenuSplitTextAtCursor {
            get {
                return ResourceManager.GetString("eMenuSplitTextAtCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Undo.
        /// </summary>
        public static string eMenuUndo {
            get {
                return ResourceManager.GetString("eMenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string eMetadataCategoryTitle {
            get {
                return ResourceManager.GetString("eMetadataCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCLI.
        /// </summary>
        public static string eMetadataCcliNumberTitle {
            get {
                return ResourceManager.GetString("eMetadataCcliNumberTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string eMetadataCopyrightTitle {
            get {
                return ResourceManager.GetString("eMetadataCopyrightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string eMetadataLanguageTitle {
            get {
                return ResourceManager.GetString("eMetadataLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string eMetadataSourceTitle {
            get {
                return ResourceManager.GetString("eMetadataSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import song from SongSelect. The text in the clipboard is not valid..
        /// </summary>
        public static string eMsgCouldNotImportFromClipboard {
            get {
                return ResourceManager.GetString("eMsgCouldNotImportFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open the song &quot;{0}&quot;. (Error: {1}).
        /// </summary>
        public static string eMsgCouldNotOpenSong {
            get {
                return ResourceManager.GetString("eMsgCouldNotOpenSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last slide in a part cannot be moved or deleted..
        /// </summary>
        public static string eMsgMoveLastSlideInPart {
            get {
                return ResourceManager.GetString("eMsgMoveLastSlideInPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This song currently uses a video background. If you change the background for this element, the video background for the whole song is replaced by the selected background. Continue?.
        /// </summary>
        public static string eMsgReplaceVideoBackground {
            get {
                return ResourceManager.GetString("eMsgReplaceVideoBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace video background?.
        /// </summary>
        public static string eMsgReplaceVideoBackgroundTitle {
            get {
                return ResourceManager.GetString("eMsgReplaceVideoBackgroundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The song &quot;{0}&quot; might contain unsaved changes. Do you want to save?.
        /// </summary>
        public static string eMsgSaveSongChanges {
            get {
                return ResourceManager.GetString("eMsgSaveSongChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string eMsgSaveSongChangesTitle {
            get {
                return ResourceManager.GetString("eMsgSaveSongChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have checked the option to use the same font size for all slides, but currently there are multiple font sizes. If you continue, the current font size will be applied to all slides. Do you really want to use a single font size?.
        /// </summary>
        public static string eMsgSingleFontSize {
            get {
                return ResourceManager.GetString("eMsgSingleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple font sizes.
        /// </summary>
        public static string eMsgSingleFontSizeTitle {
            get {
                return ResourceManager.GetString("eMsgSingleFontSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected background is a video background, but video backgrounds can only be used for the whole song. Shall this background be used for the whole song instead?.
        /// </summary>
        public static string eMsgVideoBackgroundForElement {
            get {
                return ResourceManager.GetString("eMsgVideoBackgroundForElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use video background?.
        /// </summary>
        public static string eMsgVideoBackgroundForElementTitle {
            get {
                return ResourceManager.GetString("eMsgVideoBackgroundForElementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled song.
        /// </summary>
        public static string eNewSongTitle {
            get {
                return ResourceManager.GetString("eNewSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string eToolbarFontSize {
            get {
                return ResourceManager.GetString("eToolbarFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save song and reload active presentation.
        /// </summary>
        public static string eToolbarSaveAndReload {
            get {
                return ResourceManager.GetString("eToolbarSaveAndReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show chords.
        /// </summary>
        public static string eToolbarShowChords {
            get {
                return ResourceManager.GetString("eToolbarShowChords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use font size for all slides.
        /// </summary>
        public static string eToolbarSingleFontSize {
            get {
                return ResourceManager.GetString("eToolbarSingleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t initialize directory ({0}). Please choose another one..
        /// </summary>
        public static string fsCouldNotInitDirectory {
            get {
                return ResourceManager.GetString("fsCouldNotInitDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You seem to be running WordsLive for the first time. Please choose an directory to store songs and backgrounds. If the directory does not yet exist, it will be created and populated with some example data. You can change this directory any time in the future by navigating to &quot;Settings&quot; in the menu..
        /// </summary>
        public static string fsInfo {
            get {
                return ResourceManager.GetString("fsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Start.
        /// </summary>
        public static string fsTitle {
            get {
                return ResourceManager.GetString("fsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use same directory as Powerpraise (if installed).
        /// </summary>
        public static string fsUsePowerpraiseDirectory {
            get {
                return ResourceManager.GetString("fsUsePowerpraiseDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string generalMoveDown {
            get {
                return ResourceManager.GetString("generalMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string generalMoveUp {
            get {
                return ResourceManager.GetString("generalMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string generalRemove {
            get {
                return ResourceManager.GetString("generalRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve selected multiple image files. Do you want to add them as a single slideshow? When selecting &quot;Yes&quot; you will be prompted for a location to save the slideshow. Selecting &quot;No&quot; means the images will be added one by one..
        /// </summary>
        public static string imgMsgMultipleCreateSlideshow {
            get {
                return ResourceManager.GetString("imgMsgMultipleCreateSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create slideshow?.
        /// </summary>
        public static string imgMsgMultipleCreateSlideshowTitle {
            get {
                return ResourceManager.GetString("imgMsgMultipleCreateSlideshowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        public static string nAlignmentBottom {
            get {
                return ResourceManager.GetString("nAlignmentBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string nAlignmentCenter {
            get {
                return ResourceManager.GetString("nAlignmentCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        public static string nAlignmentTop {
            get {
                return ResourceManager.GetString("nAlignmentTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string nButtonHide {
            get {
                return ResourceManager.GetString("nButtonHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string nButtonShow {
            get {
                return ResourceManager.GetString("nButtonShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string nLabelAlignment {
            get {
                return ResourceManager.GetString("nLabelAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification.
        /// </summary>
        public static string nTitle {
            get {
                return ResourceManager.GetString("nTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string paAdd {
            get {
                return ResourceManager.GetString("paAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string paFullscreen {
            get {
                return ResourceManager.GetString("paFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor:.
        /// </summary>
        public static string paMonitor {
            get {
                return ResourceManager.GetString("paMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There must be at least one valid option (no red label)..
        /// </summary>
        public static string paMsgValidOption {
            get {
                return ResourceManager.GetString("paMsgValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position (rel. to top-left corner):.
        /// </summary>
        public static string paPosition {
            get {
                return ResourceManager.GetString("paPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: {0}/{1}, Size: {2}x{3}.
        /// </summary>
        public static string paPositionSize {
            get {
                return ResourceManager.GetString("paPositionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary.
        /// </summary>
        public static string paPrimary {
            get {
                return ResourceManager.GetString("paPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string paRefresh {
            get {
                return ResourceManager.GetString("paRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary.
        /// </summary>
        public static string paSecondary {
            get {
                return ResourceManager.GetString("paSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secondary/External.
        /// </summary>
        public static string paSecondaryExternal {
            get {
                return ResourceManager.GetString("paSecondaryExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size (width, height):.
        /// </summary>
        public static string paSize {
            get {
                return ResourceManager.GetString("paSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose presentation area.
        /// </summary>
        public static string paTitle {
            get {
                return ResourceManager.GetString("paTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A part with this name already exists..
        /// </summary>
        public static string rpMsgNameAlreadyExists {
            get {
                return ResourceManager.GetString("rpMsgNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must not be empty..
        /// </summary>
        public static string rpMsgNameMustNotBeEmpty {
            get {
                return ResourceManager.GetString("rpMsgNameMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chorus;Verse #;Part #;Pre-Chorus;Bridge;Instrumental;Tag;Ending.
        /// </summary>
        public static string rpNameTemplates {
            get {
                return ResourceManager.GetString("rpNameTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name:.
        /// </summary>
        public static string rpNewNameLabel {
            get {
                return ResourceManager.GetString("rpNewNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a new name.
        /// </summary>
        public static string rpTitle {
            get {
                return ResourceManager.GetString("rpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name must not be empty..
        /// </summary>
        public static string rsMsgNameMustNotBeEmpty {
            get {
                return ResourceManager.GetString("rsMsgNameMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New name:.
        /// </summary>
        public static string rsNewNameLabel {
            get {
                return ResourceManager.GetString("rsNewNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename song.
        /// </summary>
        public static string rsTitle {
            get {
                return ResourceManager.GetString("rsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file doesn&apos;t exist..
        /// </summary>
        public static string seErrorFileDoesNotExist {
            get {
                return ResourceManager.GetString("seErrorFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder doesn&apos;t exist..
        /// </summary>
        public static string seErrorFolderDoesNotExist {
            get {
                return ResourceManager.GetString("seErrorFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be at least 0..
        /// </summary>
        public static string seErrorNegativeValue {
            get {
                return ResourceManager.GetString("seErrorNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The port number must either be 80 or at least 1024..
        /// </summary>
        public static string seErrorWrongPortNumber {
            get {
                return ResourceManager.GetString("seErrorWrongPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use VLC for audio and video playback (if available).
        /// </summary>
        public static string seExternalUseVLC {
            get {
                return ResourceManager.GetString("seExternalUseVLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data sources.
        /// </summary>
        public static string seHeaderDataSources {
            get {
                return ResourceManager.GetString("seHeaderDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backgrounds:.
        /// </summary>
        public static string seLabelBackgrounds {
            get {
                return ResourceManager.GetString("seLabelBackgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template for new songs:.
        /// </summary>
        public static string seLabelNewSongTemplate {
            get {
                return ResourceManager.GetString("seLabelNewSongTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address:.
        /// </summary>
        public static string seLabelServerAddress {
            get {
                return ResourceManager.GetString("seLabelServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string seLabelServerPassword {
            get {
                return ResourceManager.GetString("seLabelServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songs:.
        /// </summary>
        public static string seLabelSongs {
            get {
                return ResourceManager.GetString("seLabelSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition between images:.
        /// </summary>
        public static string seLabelTransitionImages {
            get {
                return ResourceManager.GetString("seLabelTransitionImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition between presentations:.
        /// </summary>
        public static string seLabelTransitionPresentations {
            get {
                return ResourceManager.GetString("seLabelTransitionPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transition between song slides:.
        /// </summary>
        public static string seLabelTransitionSlides {
            get {
                return ResourceManager.GetString("seLabelTransitionSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either the selected directory for songs or backgrounds does not exist, or the connection to the data server failed. Please update the data source settings..
        /// </summary>
        public static string seMsgInitDataError {
            get {
                return ResourceManager.GetString("seMsgInitDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server could not be started. Make sure that the port is not used by any other application..
        /// </summary>
        public static string seMsgInitServerError {
            get {
                return ResourceManager.GetString("seMsgInitServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use PowerPoint (instead of Impress) for *.odp files.
        /// </summary>
        public static string sePreferPowerpointForOdp {
            get {
                return ResourceManager.GetString("sePreferPowerpointForOdp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use PowerPoint Viewer even if Office PowerPoint is available.
        /// </summary>
        public static string sePreferPowerpointViewerToPowerpoint {
            get {
                return ResourceManager.GetString("sePreferPowerpointViewerToPowerpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local directories.
        /// </summary>
        public static string seRadioLocal {
            get {
                return ResourceManager.GetString("seRadioLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data server.
        /// </summary>
        public static string seRadioServer {
            get {
                return ResourceManager.GetString("seRadioServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string seRemotingEmbeddedServerPassword {
            get {
                return ResourceManager.GetString("seRemotingEmbeddedServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port:.
        /// </summary>
        public static string seRemotingEmbeddedServerPort {
            get {
                return ResourceManager.GetString("seRemotingEmbeddedServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable embedded display server.
        /// </summary>
        public static string seRemotingEnableEmbeddedServer {
            get {
                return ResourceManager.GetString("seRemotingEnableEmbeddedServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirect all requests over embedded data server (not recommended).
        /// </summary>
        public static string seRemotingEnableRedirect {
            get {
                return ResourceManager.GetString("seRemotingEnableRedirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Tools.
        /// </summary>
        public static string seTabExternalTools {
            get {
                return ResourceManager.GetString("seTabExternalTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string seTabGeneral {
            get {
                return ResourceManager.GetString("seTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting.
        /// </summary>
        public static string seTabRemoting {
            get {
                return ResourceManager.GetString("seTabRemoting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string seTabTemplate {
            get {
                return ResourceManager.GetString("seTabTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use template as master.
        /// </summary>
        public static string seTemplateMaster {
            get {
                return ResourceManager.GetString("seTemplateMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright: formatting.
        /// </summary>
        public static string seTemplateMasterOverrideCopyrightFormatting {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideCopyrightFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright: visibility/position.
        /// </summary>
        public static string seTemplateMasterOverrideCopyrightPosition {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideCopyrightPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite the following attributes from the template:.
        /// </summary>
        public static string seTemplateMasterOverrideFollowingAttributes {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideFollowingAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline and shadow.
        /// </summary>
        public static string seTemplateMasterOverrideOutlineShadow {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideOutlineShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: formatting.
        /// </summary>
        public static string seTemplateMasterOverrideSourceFormatting {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideSourceFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source: visibility/position.
        /// </summary>
        public static string seTemplateMasterOverrideSourcePosition {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideSourcePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text and translation: formatting.
        /// </summary>
        public static string seTemplateMasterOverrideTextFormatting {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideTextFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text and translation: positions and borders.
        /// </summary>
        public static string seTemplateMasterOverrideTextPosition {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideTextPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string seTitle {
            get {
                return ResourceManager.GetString("seTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Changes in this area take effect only after restarting WordsLive..
        /// </summary>
        public static string seWarningRelaunch {
            get {
                return ResourceManager.GetString("seWarningRelaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename:.
        /// </summary>
        public static string sfFilename {
            get {
                return ResourceManager.GetString("sfFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid filename.
        /// </summary>
        public static string sfInvalidFilename {
            get {
                return ResourceManager.GetString("sfInvalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with that name already exists. Do you want to overwrite it?.
        /// </summary>
        public static string sfMsgOverwriteExistingFile {
            get {
                return ResourceManager.GetString("sfMsgOverwriteExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overwrite existing file?.
        /// </summary>
        public static string sfMsgOverwriteExistingFileTitle {
            get {
                return ResourceManager.GetString("sfMsgOverwriteExistingFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save song.
        /// </summary>
        public static string sfTitle {
            get {
                return ResourceManager.GetString("sfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add song.
        /// </summary>
        public static string slAddSong {
            get {
                return ResourceManager.GetString("slAddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string slAdvanced {
            get {
                return ResourceManager.GetString("slAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright:.
        /// </summary>
        public static string slCopyright {
            get {
                return ResourceManager.GetString("slCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished ({0:d}).
        /// </summary>
        public static string slFinishedLoadingN {
            get {
                return ResourceManager.GetString("slFinishedLoadingN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string slGridCopyright {
            get {
                return ResourceManager.GetString("slGridCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string slGridLanguage {
            get {
                return ResourceManager.GetString("slGridLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string slGridSource {
            get {
                return ResourceManager.GetString("slGridSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string slGridTitle {
            get {
                return ResourceManager.GetString("slGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no animations.
        /// </summary>
        public static string slideAnimations0 {
            get {
                return ResourceManager.GetString("slideAnimations0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 animation.
        /// </summary>
        public static string slideAnimations1 {
            get {
                return ResourceManager.GetString("slideAnimations1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} animations.
        /// </summary>
        public static string slideAnimationsPl {
            get {
                return ResourceManager.GetString("slideAnimationsPl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide {0}.
        /// </summary>
        public static string slideDescriptionN {
            get {
                return ResourceManager.GetString("slideDescriptionN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external presentation has been closed unexpectedly. WordsLive has switched to a black screen and will try to reload the presentation..
        /// </summary>
        public static string slideErrorMsgClosedExternally {
            get {
                return ResourceManager.GetString("slideErrorMsgClosedExternally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The presentation seems to contain hidden slides. This is not correctly supported in WordsLive when using Powerpoint Viewer. You can ignore this warning and continue to navigate the presentation using &quot;Next&quot; and &quot;Previous&quot;. Selecting slides directly however will probably not work..
        /// </summary>
        public static string slideErrorMsgHiddenSlides {
            get {
                return ResourceManager.GetString("slideErrorMsgHiddenSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Hidden Slides.
        /// </summary>
        public static string slideErrorMsgHiddenSlidesTitle {
            get {
                return ResourceManager.GetString("slideErrorMsgHiddenSlidesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string slideNext {
            get {
                return ResourceManager.GetString("slideNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string slidePrevious {
            get {
                return ResourceManager.GetString("slidePrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ....
        /// </summary>
        public static string slLoading {
            get {
                return ResourceManager.GetString("slLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ({0:d}) ....
        /// </summary>
        public static string slLoadingN {
            get {
                return ResourceManager.GetString("slLoadingN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the song &quot;{0}&quot;? This operation cannot be undone..
        /// </summary>
        public static string slMsgDeleteSong {
            get {
                return ResourceManager.GetString("slMsgDeleteSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Really delete song?.
        /// </summary>
        public static string slMsgDeleteSongTitle {
            get {
                return ResourceManager.GetString("slMsgDeleteSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string slSearch {
            get {
                return ResourceManager.GetString("slSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string slSearchButton {
            get {
                return ResourceManager.GetString("slSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in song text.
        /// </summary>
        public static string slSearchInText {
            get {
                return ResourceManager.GetString("slSearchInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source:.
        /// </summary>
        public static string slSource {
            get {
                return ResourceManager.GetString("slSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Songlist.
        /// </summary>
        public static string slTitle {
            get {
                return ResourceManager.GetString("slTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outline.
        /// </summary>
        public static string ssCheckboxOutline {
            get {
                return ResourceManager.GetString("ssCheckboxOutline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shadow.
        /// </summary>
        public static string ssCheckboxShadow {
            get {
                return ResourceManager.GetString("ssCheckboxShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string ssGroupHeaderCopyright {
            get {
                return ResourceManager.GetString("ssGroupHeaderCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        public static string ssGroupHeaderFormatting {
            get {
                return ResourceManager.GetString("ssGroupHeaderFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line Spacing.
        /// </summary>
        public static string ssGroupHeaderLineSpacing {
            get {
                return ResourceManager.GetString("ssGroupHeaderLineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margins.
        /// </summary>
        public static string ssGroupHeaderMargins {
            get {
                return ResourceManager.GetString("ssGroupHeaderMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string ssGroupHeaderSource {
            get {
                return ResourceManager.GetString("ssGroupHeaderSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Alignment.
        /// </summary>
        public static string ssGroupHeaderTextAlignment {
            get {
                return ResourceManager.GetString("ssGroupHeaderTextAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string ssGroupHeaderTranslation {
            get {
                return ResourceManager.GetString("ssGroupHeaderTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom:.
        /// </summary>
        public static string ssLabelBottom {
            get {
                return ResourceManager.GetString("ssLabelBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left:.
        /// </summary>
        public static string ssLabelLeft {
            get {
                return ResourceManager.GetString("ssLabelLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing between lines:.
        /// </summary>
        public static string ssLabelLineSpacing {
            get {
                return ResourceManager.GetString("ssLabelLineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom margin:.
        /// </summary>
        public static string ssLabelMarginBottom {
            get {
                return ResourceManager.GetString("ssLabelMarginBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right margin:.
        /// </summary>
        public static string ssLabelMarginRight {
            get {
                return ResourceManager.GetString("ssLabelMarginRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top margin:.
        /// </summary>
        public static string ssLabelMarginTop {
            get {
                return ResourceManager.GetString("ssLabelMarginTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Slides.
        /// </summary>
        public static string ssLabelMetaDisplayAllSlides {
            get {
                return ResourceManager.GetString("ssLabelMetaDisplayAllSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Slide.
        /// </summary>
        public static string ssLabelMetaDisplayFirstSlide {
            get {
                return ResourceManager.GetString("ssLabelMetaDisplayFirstSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Slide.
        /// </summary>
        public static string ssLabelMetaDisplayLastSlide {
            get {
                return ResourceManager.GetString("ssLabelMetaDisplayLastSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Displayed.
        /// </summary>
        public static string ssLabelMetaDisplayNone {
            get {
                return ResourceManager.GetString("ssLabelMetaDisplayNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right:.
        /// </summary>
        public static string ssLabelRight {
            get {
                return ResourceManager.GetString("ssLabelRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction:.
        /// </summary>
        public static string ssLabelShadowDirection {
            get {
                return ResourceManager.GetString("ssLabelShadowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top:.
        /// </summary>
        public static string ssLabelTop {
            get {
                return ResourceManager.GetString("ssLabelTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block below text lines.
        /// </summary>
        public static string ssLabelTranslationBlock {
            get {
                return ResourceManager.GetString("ssLabelTranslationBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inline between text lines.
        /// </summary>
        public static string ssLabelTranslationInline {
            get {
                return ResourceManager.GetString("ssLabelTranslationInline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spacing between text and translation:.
        /// </summary>
        public static string ssLabelTranslationLineSpacing {
            get {
                return ResourceManager.GetString("ssLabelTranslationLineSpacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright/Source.
        /// </summary>
        public static string ssTabMeta {
            get {
                return ResourceManager.GetString("ssTabMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Song Text.
        /// </summary>
        public static string ssTabText {
            get {
                return ResourceManager.GetString("ssTabText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Song.
        /// </summary>
        public static string ssTitle {
            get {
                return ResourceManager.GetString("ssTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking for updates failed. Please make sure that you are connected to the internet..
        /// </summary>
        public static string updMsgFailed {
            get {
                return ResourceManager.GetString("updMsgFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of WordsLive ({0}) is available. Download now?.
        /// </summary>
        public static string updMsgNewVersion {
            get {
                return ResourceManager.GetString("updMsgNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your installation of WordsLive is up to date..
        /// </summary>
        public static string updMsgUpToDate {
            get {
                return ResourceManager.GetString("updMsgUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The display process WordsLive.Awesomium.exe was closed or crashed. WordsLive will try to reload the current presentation in order to restore it..
        /// </summary>
        public static string vAwesomiumProcessCrashed {
            get {
                return ResourceManager.GetString("vAwesomiumProcessCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display process crashed.
        /// </summary>
        public static string vAwesomiumProcessCrashedTitle {
            get {
                return ResourceManager.GetString("vAwesomiumProcessCrashedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open songlist.
        /// </summary>
        public static string veMenuShowSonglist {
            get {
                return ResourceManager.GetString("veMenuShowSonglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string veMenuWindow {
            get {
                return ResourceManager.GetString("veMenuWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string vFilterAllFiles {
            get {
                return ResourceManager.GetString("vFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supported media types.
        /// </summary>
        public static string vFilterSupportedMediaTypes {
            get {
                return ResourceManager.GetString("vFilterSupportedMediaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afterwards:.
        /// </summary>
        public static string vImagesAfterwards {
            get {
                return ResourceManager.GetString("vImagesAfterwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically advance after.
        /// </summary>
        public static string vImagesAutoAdvanceAfter {
            get {
                return ResourceManager.GetString("vImagesAutoAdvanceAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop;Start over;Blackscreen;Next item in order.
        /// </summary>
        public static string vImagesFinishActions {
            get {
                return ResourceManager.GetString("vImagesFinishActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate left.
        /// </summary>
        public static string vImagesRotateLeft {
            get {
                return ResourceManager.GetString("vImagesRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate right.
        /// </summary>
        public static string vImagesRotateRight {
            get {
                return ResourceManager.GetString("vImagesRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string vImagesSave {
            get {
                return ResourceManager.GetString("vImagesSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This slideshow is currently empty. You can add one or more photos/images by dragging them from the Windows Explorer into this area. The order of the images can also be changed afterwards..
        /// </summary>
        public static string vImagesSlideshowEmpty {
            get {
                return ResourceManager.GetString("vImagesSlideshowEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WordsLive.
        /// </summary>
        public static string vMenuAbout {
            get {
                return ResourceManager.GetString("vMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Active Presentation.
        /// </summary>
        public static string vMenuActivePresentation {
            get {
                return ResourceManager.GetString("vMenuActivePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add media.
        /// </summary>
        public static string vMenuAddMedia {
            get {
                return ResourceManager.GetString("vMenuAddMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blackscreen.
        /// </summary>
        public static string vMenuBlackscreen {
            get {
                return ResourceManager.GetString("vMenuBlackscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        public static string vMenuCheckForUpdates {
            get {
                return ResourceManager.GetString("vMenuCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose presentation area.
        /// </summary>
        public static string vMenuChoosePresentationArea {
            get {
                return ResourceManager.GetString("vMenuChoosePresentationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Slideshow ....
        /// </summary>
        public static string vMenuCreateSlideshow {
            get {
                return ResourceManager.GetString("vMenuCreateSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string vMenuExit {
            get {
                return ResourceManager.GetString("vMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string vMenuFile {
            get {
                return ResourceManager.GetString("vMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string vMenuHelp {
            get {
                return ResourceManager.GetString("vMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide presentation (show desktop).
        /// </summary>
        public static string vMenuHidePresentation {
            get {
                return ResourceManager.GetString("vMenuHidePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Media.
        /// </summary>
        public static string vMenuMedia {
            get {
                return ResourceManager.GetString("vMenuMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New portfolio.
        /// </summary>
        public static string vMenuNewPortfolio {
            get {
                return ResourceManager.GetString("vMenuNewPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Help.
        /// </summary>
        public static string vMenuOnlineManual {
            get {
                return ResourceManager.GetString("vMenuOnlineManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open portfolio.
        /// </summary>
        public static string vMenuOpenPortfolio {
            get {
                return ResourceManager.GetString("vMenuOpenPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Projection.
        /// </summary>
        public static string vMenuProjection {
            get {
                return ResourceManager.GetString("vMenuProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh active media.
        /// </summary>
        public static string vMenuRefresh {
            get {
                return ResourceManager.GetString("vMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save portfolio.
        /// </summary>
        public static string vMenuSavePortfolio {
            get {
                return ResourceManager.GetString("vMenuSavePortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save portfolio _as.
        /// </summary>
        public static string vMenuSavePortfolioAs {
            get {
                return ResourceManager.GetString("vMenuSavePortfolioAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string vMenuSettings {
            get {
                return ResourceManager.GetString("vMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show chords in presentation.
        /// </summary>
        public static string vMenuShowChords {
            get {
                return ResourceManager.GetString("vMenuShowChords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open editor window.
        /// </summary>
        public static string vMenuShowEditorWindow {
            get {
                return ResourceManager.GetString("vMenuShowEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show notification.
        /// </summary>
        public static string vMenuShowNotification {
            get {
                return ResourceManager.GetString("vMenuShowNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show presentation.
        /// </summary>
        public static string vMenuShowPresentation {
            get {
                return ResourceManager.GetString("vMenuShowPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Song_list.
        /// </summary>
        public static string vMenuShowSonglist {
            get {
                return ResourceManager.GetString("vMenuShowSonglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show test image.
        /// </summary>
        public static string vMenuShowTestImage {
            get {
                return ResourceManager.GetString("vMenuShowTestImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swap text and translation.
        /// </summary>
        public static string vMenuSwapTextAndTranslation {
            get {
                return ResourceManager.GetString("vMenuSwapTextAndTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use single background for all songs.
        /// </summary>
        public static string vMenuUsePortfolioBackground {
            get {
                return ResourceManager.GetString("vMenuUsePortfolioBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} doesn&apos;t exist..
        /// </summary>
        public static string vMsgActivateFileNotFoundMedia {
            get {
                return ResourceManager.GetString("vMsgActivateFileNotFoundMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} cannot be shown, because its format is not supported..
        /// </summary>
        public static string vMsgActivateUnsupportedMedia {
            get {
                return ResourceManager.GetString("vMsgActivateUnsupportedMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current portfolio might contain unsaved changes. Do you want to save them?.
        /// </summary>
        public static string vMsgSavePortfolioChanges {
            get {
                return ResourceManager.GetString("vMsgSavePortfolioChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes?.
        /// </summary>
        public static string vMsgSavePortfolioChangesTitle {
            get {
                return ResourceManager.GetString("vMsgSavePortfolioChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load portfolio..
        /// </summary>
        public static string vMsgUnableToLoadPortfolio {
            get {
                return ResourceManager.GetString("vMsgUnableToLoadPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preview available.
        /// </summary>
        public static string vNoPreviewAvailable {
            get {
                return ResourceManager.GetString("vNoPreviewAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string vOrderContextMenuRefresh {
            get {
                return ResourceManager.GetString("vOrderContextMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string vOrderContextMenuShow {
            get {
                return ResourceManager.GetString("vOrderContextMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string vPanelOrder {
            get {
                return ResourceManager.GetString("vPanelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string vPanelPreview {
            get {
                return ResourceManager.GetString("vPanelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit to CCLI Online Reporting.
        /// </summary>
        public static string vSubmitCcliOlr {
            get {
                return ResourceManager.GetString("vSubmitCcliOlr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New portfolio.
        /// </summary>
        public static string vTitleUnnamedPortfolio {
            get {
                return ResourceManager.GetString("vTitleUnnamedPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open active song in editor.
        /// </summary>
        public static string vToolbarEditActiveSong {
            get {
                return ResourceManager.GetString("vToolbarEditActiveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception occured while running WordsLive. This should not happen. You can try to ignore the exception and continue to work with WordsLive, though this might lead to instabilities..
        /// </summary>
        public static string xUnhandledException {
            get {
                return ResourceManager.GetString("xUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string xUnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("xUnhandledExceptionTitle", resourceCulture);
            }
        }
    }
}
