//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18052
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordsLive.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordsLive.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loop ähnelt.
        /// </summary>
        public static string avCheckboxLoop {
            get {
                return ResourceManager.GetString("avCheckboxLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset offset: ähnelt.
        /// </summary>
        public static string avLabelResetOffset {
            get {
                return ResourceManager.GetString("avLabelResetOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use current position as: ähnelt.
        /// </summary>
        public static string avLabelSetOffset {
            get {
                return ResourceManager.GetString("avLabelSetOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Volume: ähnelt.
        /// </summary>
        public static string avLabelVolume {
            get {
                return ResourceManager.GetString("avLabelVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End ähnelt.
        /// </summary>
        public static string avOffsetEnd {
            get {
                return ResourceManager.GetString("avOffsetEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Start ähnelt.
        /// </summary>
        public static string avOffsetStart {
            get {
                return ResourceManager.GetString("avOffsetStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pause ähnelt.
        /// </summary>
        public static string avTooltipPause {
            get {
                return ResourceManager.GetString("avTooltipPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Play ähnelt.
        /// </summary>
        public static string avTooltipPlay {
            get {
                return ResourceManager.GetString("avTooltipPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop ähnelt.
        /// </summary>
        public static string avTooltipStop {
            get {
                return ResourceManager.GetString("avTooltipStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply this background to all slides ähnelt.
        /// </summary>
        public static string cbApplyToAllSlides {
            get {
                return ResourceManager.GetString("cbApplyToAllSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The background currently in use for this song was not found and is replaced by a black background. ähnelt.
        /// </summary>
        public static string cbMsgNotFound {
            get {
                return ResourceManager.GetString("cbMsgNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Background not found ähnelt.
        /// </summary>
        public static string cbMsgNotFoundTitle {
            get {
                return ResourceManager.GetString("cbMsgNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview size: ähnelt.
        /// </summary>
        public static string cbPreviewSize {
            get {
                return ResourceManager.GetString("cbPreviewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose background ähnelt.
        /// </summary>
        public static string cbTitle {
            get {
                return ResourceManager.GetString("cbTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use single color ähnelt.
        /// </summary>
        public static string cbUseSingleColor {
            get {
                return ResourceManager.GetString("cbUseSingleColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Abort ähnelt.
        /// </summary>
        public static string dialogAbort {
            get {
                return ResourceManager.GetString("dialogAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        public static string dialogCancel {
            get {
                return ResourceManager.GetString("dialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close ähnelt.
        /// </summary>
        public static string dialogClose {
            get {
                return ResourceManager.GetString("dialogClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        public static string dialogError {
            get {
                return ResourceManager.GetString("dialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ignore ähnelt.
        /// </summary>
        public static string dialogIgnore {
            get {
                return ResourceManager.GetString("dialogIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        public static string dialogOK {
            get {
                return ResourceManager.GetString("dialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string dialogRefresh {
            get {
                return ResourceManager.GetString("dialogRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current page ähnelt.
        /// </summary>
        public static string docCurrentPage {
            get {
                return ResourceManager.GetString("docCurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next page ähnelt.
        /// </summary>
        public static string docNextPage {
            get {
                return ResourceManager.GetString("docNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Page scale ähnelt.
        /// </summary>
        public static string docPageScale {
            get {
                return ResourceManager.GetString("docPageScale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Previous page ähnelt.
        /// </summary>
        public static string docPreviousPage {
            get {
                return ResourceManager.GetString("docPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fit to width ähnelt.
        /// </summary>
        public static string docScaleFitToWidth {
            get {
                return ResourceManager.GetString("docScaleFitToWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Whole page ähnelt.
        /// </summary>
        public static string docScaleWholePage {
            get {
                return ResourceManager.GetString("docScaleWholePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open in editor ähnelt.
        /// </summary>
        public static string eCommandOpenInEditor {
            get {
                return ResourceManager.GetString("eCommandOpenInEditor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add slide/part ähnelt.
        /// </summary>
        public static string eGridAddElementButton {
            get {
                return ResourceManager.GetString("eGridAddElementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add part ähnelt.
        /// </summary>
        public static string eGridContextAddPart {
            get {
                return ResourceManager.GetString("eGridContextAddPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add slide ähnelt.
        /// </summary>
        public static string eGridContextAddSlide {
            get {
                return ResourceManager.GetString("eGridContextAddSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Duplicate slide ähnelt.
        /// </summary>
        public static string eGridContextDuplicateSlide {
            get {
                return ResourceManager.GetString("eGridContextDuplicateSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove part ähnelt.
        /// </summary>
        public static string eGridContextRemovePart {
            get {
                return ResourceManager.GetString("eGridContextRemovePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove slide ähnelt.
        /// </summary>
        public static string eGridContextRemoveSlide {
            get {
                return ResourceManager.GetString("eGridContextRemoveSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename ähnelt.
        /// </summary>
        public static string eGridContextRename {
            get {
                return ResourceManager.GetString("eGridContextRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename song ähnelt.
        /// </summary>
        public static string eGridContextRenameSong {
            get {
                return ResourceManager.GetString("eGridContextRenameSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swap text and translation ähnelt.
        /// </summary>
        public static string eGridContextSwapTextAndTranslation {
            get {
                return ResourceManager.GetString("eGridContextSwapTextAndTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die English;German;Spanish ähnelt.
        /// </summary>
        public static string eGridLanguages {
            get {
                return ResourceManager.GetString("eGridLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text: ähnelt.
        /// </summary>
        public static string eGridLanguageText {
            get {
                return ResourceManager.GetString("eGridLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translation: ähnelt.
        /// </summary>
        public static string eGridLanguageTranslation {
            get {
                return ResourceManager.GetString("eGridLanguageTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add selected part to order ähnelt.
        /// </summary>
        public static string eGridOrderAddButton {
            get {
                return ResourceManager.GetString("eGridOrderAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Order ähnelt.
        /// </summary>
        public static string eGridOrderHeader {
            get {
                return ResourceManager.GetString("eGridOrderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move part down ähnelt.
        /// </summary>
        public static string eGridOrderMoveDownButton {
            get {
                return ResourceManager.GetString("eGridOrderMoveDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move part up ähnelt.
        /// </summary>
        public static string eGridOrderMoveUpButton {
            get {
                return ResourceManager.GetString("eGridOrderMoveUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove part from order ähnelt.
        /// </summary>
        public static string eGridOrderRemoveButton {
            get {
                return ResourceManager.GetString("eGridOrderRemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show slides ähnelt.
        /// </summary>
        public static string eGridOrderShowSlidesCheckbox {
            get {
                return ResourceManager.GetString("eGridOrderShowSlidesCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parts ähnelt.
        /// </summary>
        public static string eGridPartsHeader {
            get {
                return ResourceManager.GetString("eGridPartsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview ähnelt.
        /// </summary>
        public static string eGridPreviewHeader {
            get {
                return ResourceManager.GetString("eGridPreviewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slide ähnelt.
        /// </summary>
        public static string eGridSlideTitle {
            get {
                return ResourceManager.GetString("eGridSlideTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Number: ähnelt.
        /// </summary>
        public static string eGridSourceNumberLabel {
            get {
                return ResourceManager.GetString("eGridSourceNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Songbook: ähnelt.
        /// </summary>
        public static string eGridSourceSongbookLabel {
            get {
                return ResourceManager.GetString("eGridSourceSongbookLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spell check ähnelt.
        /// </summary>
        public static string eGridSpellCheckCheckbox {
            get {
                return ResourceManager.GetString("eGridSpellCheckCheckbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text ähnelt.
        /// </summary>
        public static string eGridTextHeader {
            get {
                return ResourceManager.GetString("eGridTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Translation ähnelt.
        /// </summary>
        public static string eGridTranslation {
            get {
                return ResourceManager.GetString("eGridTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add song to current portfolio ähnelt.
        /// </summary>
        public static string eMenuAddToPortfolio {
            get {
                return ResourceManager.GetString("eMenuAddToPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close song ähnelt.
        /// </summary>
        public static string eMenuCloseSong {
            get {
                return ResourceManager.GetString("eMenuCloseSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Edit ähnelt.
        /// </summary>
        public static string eMenuEdit {
            get {
                return ResourceManager.GetString("eMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit chords ähnelt.
        /// </summary>
        public static string eMenuEditChords {
            get {
                return ResourceManager.GetString("eMenuEditChords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Export song ähnelt.
        /// </summary>
        public static string eMenuExportSong {
            get {
                return ResourceManager.GetString("eMenuExportSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _File ähnelt.
        /// </summary>
        public static string eMenuFile {
            get {
                return ResourceManager.GetString("eMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Format song ähnelt.
        /// </summary>
        public static string eMenuFormatSong {
            get {
                return ResourceManager.GetString("eMenuFormatSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Import SongSelect song from Clipboard ähnelt.
        /// </summary>
        public static string eMenuImportFromClipboard {
            get {
                return ResourceManager.GetString("eMenuImportFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New song ähnelt.
        /// </summary>
        public static string eMenuNewSong {
            get {
                return ResourceManager.GetString("eMenuNewSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open song ähnelt.
        /// </summary>
        public static string eMenuOpenSong {
            get {
                return ResourceManager.GetString("eMenuOpenSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Redo ähnelt.
        /// </summary>
        public static string eMenuRedo {
            get {
                return ResourceManager.GetString("eMenuRedo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save song ähnelt.
        /// </summary>
        public static string eMenuSaveSong {
            get {
                return ResourceManager.GetString("eMenuSaveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save song as ähnelt.
        /// </summary>
        public static string eMenuSaveSongAs {
            get {
                return ResourceManager.GetString("eMenuSaveSongAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show presenter window ähnelt.
        /// </summary>
        public static string eMenuShowPresenter {
            get {
                return ResourceManager.GetString("eMenuShowPresenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Split text at cursor position ähnelt.
        /// </summary>
        public static string eMenuSplitTextAtCursor {
            get {
                return ResourceManager.GetString("eMenuSplitTextAtCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Undo ähnelt.
        /// </summary>
        public static string eMenuUndo {
            get {
                return ResourceManager.GetString("eMenuUndo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Category ähnelt.
        /// </summary>
        public static string eMetadataCategoryTitle {
            get {
                return ResourceManager.GetString("eMetadataCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright ähnelt.
        /// </summary>
        public static string eMetadataCopyrightTitle {
            get {
                return ResourceManager.GetString("eMetadataCopyrightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string eMetadataLanguageTitle {
            get {
                return ResourceManager.GetString("eMetadataLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source ähnelt.
        /// </summary>
        public static string eMetadataSourceTitle {
            get {
                return ResourceManager.GetString("eMetadataSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Could not import song from SongSelect. The text in the clipboard is not valid. ähnelt.
        /// </summary>
        public static string eMsgCouldNotImportFromClipboard {
            get {
                return ResourceManager.GetString("eMsgCouldNotImportFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not open the song &quot;{0}&quot;. (Error: {1}) ähnelt.
        /// </summary>
        public static string eMsgCouldNotOpenSong {
            get {
                return ResourceManager.GetString("eMsgCouldNotOpenSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The last slide in a part cannot be moved or deleted. ähnelt.
        /// </summary>
        public static string eMsgMoveLastSlideInPart {
            get {
                return ResourceManager.GetString("eMsgMoveLastSlideInPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This song currently uses a video background. If you change the background for this element, the video background for the whole song is replaced by the selected background. Continue? ähnelt.
        /// </summary>
        public static string eMsgReplaceVideoBackground {
            get {
                return ResourceManager.GetString("eMsgReplaceVideoBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Replace video background? ähnelt.
        /// </summary>
        public static string eMsgReplaceVideoBackgroundTitle {
            get {
                return ResourceManager.GetString("eMsgReplaceVideoBackgroundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The song &quot;{0}&quot; might contain unsaved changes. Do you want to save? ähnelt.
        /// </summary>
        public static string eMsgSaveSongChanges {
            get {
                return ResourceManager.GetString("eMsgSaveSongChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes? ähnelt.
        /// </summary>
        public static string eMsgSaveSongChangesTitle {
            get {
                return ResourceManager.GetString("eMsgSaveSongChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You have checked the option to use the same font size for all slides, but currently there are multiple font sizes. If you continue, the current font size will be applied to all slides. Do you really want to use a single font size? ähnelt.
        /// </summary>
        public static string eMsgSingleFontSize {
            get {
                return ResourceManager.GetString("eMsgSingleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Multiple font sizes ähnelt.
        /// </summary>
        public static string eMsgSingleFontSizeTitle {
            get {
                return ResourceManager.GetString("eMsgSingleFontSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The selected background is a video background, but video backgrounds can only be used for the whole song. Shall this background be used for the whole song instead? ähnelt.
        /// </summary>
        public static string eMsgVideoBackgroundForElement {
            get {
                return ResourceManager.GetString("eMsgVideoBackgroundForElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use video background? ähnelt.
        /// </summary>
        public static string eMsgVideoBackgroundForElementTitle {
            get {
                return ResourceManager.GetString("eMsgVideoBackgroundForElementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Untitled song ähnelt.
        /// </summary>
        public static string eNewSongTitle {
            get {
                return ResourceManager.GetString("eNewSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change background for selected element ähnelt.
        /// </summary>
        public static string eToolbarChangeBackground {
            get {
                return ResourceManager.GetString("eToolbarChangeBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Font size ähnelt.
        /// </summary>
        public static string eToolbarFontSize {
            get {
                return ResourceManager.GetString("eToolbarFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save song and reload active presentation ähnelt.
        /// </summary>
        public static string eToolbarSaveAndReload {
            get {
                return ResourceManager.GetString("eToolbarSaveAndReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show chords ähnelt.
        /// </summary>
        public static string eToolbarShowChords {
            get {
                return ResourceManager.GetString("eToolbarShowChords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use font size for all slides ähnelt.
        /// </summary>
        public static string eToolbarSingleFontSize {
            get {
                return ResourceManager.GetString("eToolbarSingleFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You&apos;ve selected multiple image files. Do you want to add them as a single slideshow? When selecting &quot;Yes&quot; you will be prompted for a location to save the slideshow. Selecting &quot;No&quot; means the images will be added one by one. ähnelt.
        /// </summary>
        public static string imgMsgMultipleCreateSlideshow {
            get {
                return ResourceManager.GetString("imgMsgMultipleCreateSlideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create slideshow? ähnelt.
        /// </summary>
        public static string imgMsgMultipleCreateSlideshowTitle {
            get {
                return ResourceManager.GetString("imgMsgMultipleCreateSlideshowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bottom ähnelt.
        /// </summary>
        public static string nAlignmentBottom {
            get {
                return ResourceManager.GetString("nAlignmentBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Center ähnelt.
        /// </summary>
        public static string nAlignmentCenter {
            get {
                return ResourceManager.GetString("nAlignmentCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Top ähnelt.
        /// </summary>
        public static string nAlignmentTop {
            get {
                return ResourceManager.GetString("nAlignmentTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide ähnelt.
        /// </summary>
        public static string nButtonHide {
            get {
                return ResourceManager.GetString("nButtonHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show ähnelt.
        /// </summary>
        public static string nButtonShow {
            get {
                return ResourceManager.GetString("nButtonShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alignment ähnelt.
        /// </summary>
        public static string nLabelAlignment {
            get {
                return ResourceManager.GetString("nLabelAlignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show notification ähnelt.
        /// </summary>
        public static string nTitle {
            get {
                return ResourceManager.GetString("nTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string paAdd {
            get {
                return ResourceManager.GetString("paAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fullscreen ähnelt.
        /// </summary>
        public static string paFullscreen {
            get {
                return ResourceManager.GetString("paFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monitor: ähnelt.
        /// </summary>
        public static string paMonitor {
            get {
                return ResourceManager.GetString("paMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move down ähnelt.
        /// </summary>
        public static string paMoveDown {
            get {
                return ResourceManager.GetString("paMoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Move up ähnelt.
        /// </summary>
        public static string paMoveUp {
            get {
                return ResourceManager.GetString("paMoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die There must be at least one valid option (no red label). ähnelt.
        /// </summary>
        public static string paMsgValidOption {
            get {
                return ResourceManager.GetString("paMsgValidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position (rel. to top-left corner): ähnelt.
        /// </summary>
        public static string paPosition {
            get {
                return ResourceManager.GetString("paPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position: {0}/{1}, Size: {2}x{3} ähnelt.
        /// </summary>
        public static string paPositionSize {
            get {
                return ResourceManager.GetString("paPositionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Primary ähnelt.
        /// </summary>
        public static string paPrimary {
            get {
                return ResourceManager.GetString("paPrimary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string paRefresh {
            get {
                return ResourceManager.GetString("paRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string paRemove {
            get {
                return ResourceManager.GetString("paRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Secondary ähnelt.
        /// </summary>
        public static string paSecondary {
            get {
                return ResourceManager.GetString("paSecondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Secondary/External ähnelt.
        /// </summary>
        public static string paSecondaryExternal {
            get {
                return ResourceManager.GetString("paSecondaryExternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Size (width, height): ähnelt.
        /// </summary>
        public static string paSize {
            get {
                return ResourceManager.GetString("paSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose presentation area ähnelt.
        /// </summary>
        public static string paTitle {
            get {
                return ResourceManager.GetString("paTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A part with this name already exists. ähnelt.
        /// </summary>
        public static string rpMsgNameAlreadyExists {
            get {
                return ResourceManager.GetString("rpMsgNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name must not be empty. ähnelt.
        /// </summary>
        public static string rpMsgNameMustNotBeEmpty {
            get {
                return ResourceManager.GetString("rpMsgNameMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Chorus;Verse #;Part #;Pre-Chorus;Bridge;Instrumental;Tag;Ending ähnelt.
        /// </summary>
        public static string rpNameTemplates {
            get {
                return ResourceManager.GetString("rpNameTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New name: ähnelt.
        /// </summary>
        public static string rpNewNameLabel {
            get {
                return ResourceManager.GetString("rpNewNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose a new name ähnelt.
        /// </summary>
        public static string rpTitle {
            get {
                return ResourceManager.GetString("rpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The name must not be empty. ähnelt.
        /// </summary>
        public static string rsMsgNameMustNotBeEmpty {
            get {
                return ResourceManager.GetString("rsMsgNameMustNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New name: ähnelt.
        /// </summary>
        public static string rsNewNameLabel {
            get {
                return ResourceManager.GetString("rsNewNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rename song ähnelt.
        /// </summary>
        public static string rsTitle {
            get {
                return ResourceManager.GetString("rsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file doesn&apos;t exist. ähnelt.
        /// </summary>
        public static string seErrorFileDoesNotExist {
            get {
                return ResourceManager.GetString("seErrorFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The folder doesn&apos;t exist. ähnelt.
        /// </summary>
        public static string seErrorFolderDoesNotExist {
            get {
                return ResourceManager.GetString("seErrorFolderDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The value must be at least 0. ähnelt.
        /// </summary>
        public static string seErrorNegativeValue {
            get {
                return ResourceManager.GetString("seErrorNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The port number must either be 80 or at least 1024. ähnelt.
        /// </summary>
        public static string seErrorWrongPortNumber {
            get {
                return ResourceManager.GetString("seErrorWrongPortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data sources ähnelt.
        /// </summary>
        public static string seHeaderDataSources {
            get {
                return ResourceManager.GetString("seHeaderDataSources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Backgrounds: ähnelt.
        /// </summary>
        public static string seLabelBackgrounds {
            get {
                return ResourceManager.GetString("seLabelBackgrounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template for new songs: ähnelt.
        /// </summary>
        public static string seLabelNewSongTemplate {
            get {
                return ResourceManager.GetString("seLabelNewSongTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Address: ähnelt.
        /// </summary>
        public static string seLabelServerAddress {
            get {
                return ResourceManager.GetString("seLabelServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password: ähnelt.
        /// </summary>
        public static string seLabelServerPassword {
            get {
                return ResourceManager.GetString("seLabelServerPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Songs: ähnelt.
        /// </summary>
        public static string seLabelSongs {
            get {
                return ResourceManager.GetString("seLabelSongs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transition between images: ähnelt.
        /// </summary>
        public static string seLabelTransitionImages {
            get {
                return ResourceManager.GetString("seLabelTransitionImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transition between presentations: ähnelt.
        /// </summary>
        public static string seLabelTransitionPresentations {
            get {
                return ResourceManager.GetString("seLabelTransitionPresentations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transition between song slides: ähnelt.
        /// </summary>
        public static string seLabelTransitionSlides {
            get {
                return ResourceManager.GetString("seLabelTransitionSlides", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Either the selected directory for songs or backgrounds does not exist, or the connection to the data server failed. Please update the data source settings. ähnelt.
        /// </summary>
        public static string seMsgInitDataError {
            get {
                return ResourceManager.GetString("seMsgInitDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The server could not be started. Make sure that the port is not used by any other application. ähnelt.
        /// </summary>
        public static string seMsgInitServerError {
            get {
                return ResourceManager.GetString("seMsgInitServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Local directories ähnelt.
        /// </summary>
        public static string seRadioLocal {
            get {
                return ResourceManager.GetString("seRadioLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data server ähnelt.
        /// </summary>
        public static string seRadioServer {
            get {
                return ResourceManager.GetString("seRadioServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string seTabGeneral {
            get {
                return ResourceManager.GetString("seTabGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Template ähnelt.
        /// </summary>
        public static string seTabTemplate {
            get {
                return ResourceManager.GetString("seTabTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use template as master ähnelt.
        /// </summary>
        public static string seTemplateMaster {
            get {
                return ResourceManager.GetString("seTemplateMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright: formatting ähnelt.
        /// </summary>
        public static string seTemplateMasterOverrideCopyrightFormatting {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideCopyrightFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright: visibility/position ähnelt.
        /// </summary>
        public static string seTemplateMasterOverrideCopyrightPosition {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideCopyrightPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite the following attributes from the template: ähnelt.
        /// </summary>
        public static string seTemplateMasterOverrideFollowingAttributes {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideFollowingAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outline and shadow ähnelt.
        /// </summary>
        public static string seTemplateMasterOverrideOutlineShadow {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideOutlineShadow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source: formatting ähnelt.
        /// </summary>
        public static string seTemplateMasterOverrideSourceFormatting {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideSourceFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source: visibility/position ähnelt.
        /// </summary>
        public static string seTemplateMasterOverrideSourcePosition {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideSourcePosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text and translation: formatting ähnelt.
        /// </summary>
        public static string seTemplateMasterOverrideTextFormatting {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideTextFormatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Text and translation: positions and borders ähnelt.
        /// </summary>
        public static string seTemplateMasterOverrideTextPosition {
            get {
                return ResourceManager.GetString("seTemplateMasterOverrideTextPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string seTitle {
            get {
                return ResourceManager.GetString("seTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Warning: Changes in this area take effect only after restarting WordsLive. ähnelt.
        /// </summary>
        public static string seWarningRelaunch {
            get {
                return ResourceManager.GetString("seWarningRelaunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Filename: ähnelt.
        /// </summary>
        public static string sfFilename {
            get {
                return ResourceManager.GetString("sfFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Invalid filename ähnelt.
        /// </summary>
        public static string sfInvalidFilename {
            get {
                return ResourceManager.GetString("sfInvalidFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A file with that name already exists. Do you want to overwrite it? ähnelt.
        /// </summary>
        public static string sfMsgOverwriteExistingFile {
            get {
                return ResourceManager.GetString("sfMsgOverwriteExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Overwrite existing file? ähnelt.
        /// </summary>
        public static string sfMsgOverwriteExistingFileTitle {
            get {
                return ResourceManager.GetString("sfMsgOverwriteExistingFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save song ähnelt.
        /// </summary>
        public static string sfTitle {
            get {
                return ResourceManager.GetString("sfTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add song ähnelt.
        /// </summary>
        public static string slAddSong {
            get {
                return ResourceManager.GetString("slAddSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Advanced ähnelt.
        /// </summary>
        public static string slAdvanced {
            get {
                return ResourceManager.GetString("slAdvanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright: ähnelt.
        /// </summary>
        public static string slCopyright {
            get {
                return ResourceManager.GetString("slCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Finished ({0:d}) ähnelt.
        /// </summary>
        public static string slFinishedLoadingN {
            get {
                return ResourceManager.GetString("slFinishedLoadingN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Copyright ähnelt.
        /// </summary>
        public static string slGridCopyright {
            get {
                return ResourceManager.GetString("slGridCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string slGridLanguage {
            get {
                return ResourceManager.GetString("slGridLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source ähnelt.
        /// </summary>
        public static string slGridSource {
            get {
                return ResourceManager.GetString("slGridSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Title ähnelt.
        /// </summary>
        public static string slGridTitle {
            get {
                return ResourceManager.GetString("slGridTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading ... ähnelt.
        /// </summary>
        public static string slLoading {
            get {
                return ResourceManager.GetString("slLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading ({0:d}) ... ähnelt.
        /// </summary>
        public static string slLoadingN {
            get {
                return ResourceManager.GetString("slLoadingN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you really want to delete the song &quot;{0}&quot;? This operation cannot be undone. ähnelt.
        /// </summary>
        public static string slMsgDeleteSong {
            get {
                return ResourceManager.GetString("slMsgDeleteSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Really delete song? ähnelt.
        /// </summary>
        public static string slMsgDeleteSongTitle {
            get {
                return ResourceManager.GetString("slMsgDeleteSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string slSearch {
            get {
                return ResourceManager.GetString("slSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search ähnelt.
        /// </summary>
        public static string slSearchButton {
            get {
                return ResourceManager.GetString("slSearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Search in song text ähnelt.
        /// </summary>
        public static string slSearchInText {
            get {
                return ResourceManager.GetString("slSearchInText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Source: ähnelt.
        /// </summary>
        public static string slSource {
            get {
                return ResourceManager.GetString("slSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Songlist ähnelt.
        /// </summary>
        public static string slTitle {
            get {
                return ResourceManager.GetString("slTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Checking for updates failed. Please make sure that you are connected to the internet. ähnelt.
        /// </summary>
        public static string updMsgFailed {
            get {
                return ResourceManager.GetString("updMsgFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die A new version of WordsLive ({0}) is available. Download now? ähnelt.
        /// </summary>
        public static string updMsgNewVersion {
            get {
                return ResourceManager.GetString("updMsgNewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Your installation of WordsLive is up to date. ähnelt.
        /// </summary>
        public static string updMsgUpToDate {
            get {
                return ResourceManager.GetString("updMsgUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The display process WordsLive.Awesomium.exe was closed or crashed. WordsLive will try to reload the current presentation in order to restore it. ähnelt.
        /// </summary>
        public static string vAwesomiumProcessCrashed {
            get {
                return ResourceManager.GetString("vAwesomiumProcessCrashed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Display process crashed ähnelt.
        /// </summary>
        public static string vAwesomiumProcessCrashedTitle {
            get {
                return ResourceManager.GetString("vAwesomiumProcessCrashedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open songlist ähnelt.
        /// </summary>
        public static string veMenuShowSonglist {
            get {
                return ResourceManager.GetString("veMenuShowSonglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Window ähnelt.
        /// </summary>
        public static string veMenuWindow {
            get {
                return ResourceManager.GetString("veMenuWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All files ähnelt.
        /// </summary>
        public static string vFilterAllFiles {
            get {
                return ResourceManager.GetString("vFilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Supported media types ähnelt.
        /// </summary>
        public static string vFilterSupportedMediaTypes {
            get {
                return ResourceManager.GetString("vFilterSupportedMediaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Afterwards: ähnelt.
        /// </summary>
        public static string vImagesAfterwards {
            get {
                return ResourceManager.GetString("vImagesAfterwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Automatically advance after ähnelt.
        /// </summary>
        public static string vImagesAutoAdvanceAfter {
            get {
                return ResourceManager.GetString("vImagesAutoAdvanceAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string vImagesContextMenuRemove {
            get {
                return ResourceManager.GetString("vImagesContextMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Stop;Start over;Blackscreen;Next item in order ähnelt.
        /// </summary>
        public static string vImagesFinishActions {
            get {
                return ResourceManager.GetString("vImagesFinishActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotate left ähnelt.
        /// </summary>
        public static string vImagesRotateLeft {
            get {
                return ResourceManager.GetString("vImagesRotateLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rotate right ähnelt.
        /// </summary>
        public static string vImagesRotateRight {
            get {
                return ResourceManager.GetString("vImagesRotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string vImagesSave {
            get {
                return ResourceManager.GetString("vImagesSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About WordsLive ähnelt.
        /// </summary>
        public static string vMenuAbout {
            get {
                return ResourceManager.GetString("vMenuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Active Presentation ähnelt.
        /// </summary>
        public static string vMenuActivePresentation {
            get {
                return ResourceManager.GetString("vMenuActivePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add media ähnelt.
        /// </summary>
        public static string vMenuAddMedia {
            get {
                return ResourceManager.GetString("vMenuAddMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Blackscreen ähnelt.
        /// </summary>
        public static string vMenuBlackscreen {
            get {
                return ResourceManager.GetString("vMenuBlackscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Check for Updates ähnelt.
        /// </summary>
        public static string vMenuCheckForUpdates {
            get {
                return ResourceManager.GetString("vMenuCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Choose presentation area ähnelt.
        /// </summary>
        public static string vMenuChoosePresentationArea {
            get {
                return ResourceManager.GetString("vMenuChoosePresentationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Exit ähnelt.
        /// </summary>
        public static string vMenuExit {
            get {
                return ResourceManager.GetString("vMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _File ähnelt.
        /// </summary>
        public static string vMenuFile {
            get {
                return ResourceManager.GetString("vMenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Help ähnelt.
        /// </summary>
        public static string vMenuHelp {
            get {
                return ResourceManager.GetString("vMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hide presentation (show desktop) ähnelt.
        /// </summary>
        public static string vMenuHidePresentation {
            get {
                return ResourceManager.GetString("vMenuHidePresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Media ähnelt.
        /// </summary>
        public static string vMenuMedia {
            get {
                return ResourceManager.GetString("vMenuMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _New portfolio ähnelt.
        /// </summary>
        public static string vMenuNewPortfolio {
            get {
                return ResourceManager.GetString("vMenuNewPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Online Help ähnelt.
        /// </summary>
        public static string vMenuOnlineManual {
            get {
                return ResourceManager.GetString("vMenuOnlineManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Open portfolio ähnelt.
        /// </summary>
        public static string vMenuOpenPortfolio {
            get {
                return ResourceManager.GetString("vMenuOpenPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Projection ähnelt.
        /// </summary>
        public static string vMenuProjection {
            get {
                return ResourceManager.GetString("vMenuProjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh active media ähnelt.
        /// </summary>
        public static string vMenuRefresh {
            get {
                return ResourceManager.GetString("vMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die _Save portfolio ähnelt.
        /// </summary>
        public static string vMenuSavePortfolio {
            get {
                return ResourceManager.GetString("vMenuSavePortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save portfolio _as ähnelt.
        /// </summary>
        public static string vMenuSavePortfolioAs {
            get {
                return ResourceManager.GetString("vMenuSavePortfolioAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string vMenuSettings {
            get {
                return ResourceManager.GetString("vMenuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show chords in presentation ähnelt.
        /// </summary>
        public static string vMenuShowChords {
            get {
                return ResourceManager.GetString("vMenuShowChords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open editor window ähnelt.
        /// </summary>
        public static string vMenuShowEditorWindow {
            get {
                return ResourceManager.GetString("vMenuShowEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show notification ähnelt.
        /// </summary>
        public static string vMenuShowNotification {
            get {
                return ResourceManager.GetString("vMenuShowNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show presentation ähnelt.
        /// </summary>
        public static string vMenuShowPresentation {
            get {
                return ResourceManager.GetString("vMenuShowPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open Song_list ähnelt.
        /// </summary>
        public static string vMenuShowSonglist {
            get {
                return ResourceManager.GetString("vMenuShowSonglist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show test image ähnelt.
        /// </summary>
        public static string vMenuShowTestImage {
            get {
                return ResourceManager.GetString("vMenuShowTestImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Swap text and translation ähnelt.
        /// </summary>
        public static string vMenuSwapTextAndTranslation {
            get {
                return ResourceManager.GetString("vMenuSwapTextAndTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use single background for all songs ähnelt.
        /// </summary>
        public static string vMenuUsePortfolioBackground {
            get {
                return ResourceManager.GetString("vMenuUsePortfolioBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file {0} doesn&apos;t exist. ähnelt.
        /// </summary>
        public static string vMsgActivateFileNotFoundMedia {
            get {
                return ResourceManager.GetString("vMsgActivateFileNotFoundMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The file {0} cannot be shown, because its format is not supported. ähnelt.
        /// </summary>
        public static string vMsgActivateUnsupportedMedia {
            get {
                return ResourceManager.GetString("vMsgActivateUnsupportedMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The current portfolio might contain unsaved changes. Do you want to save them? ähnelt.
        /// </summary>
        public static string vMsgSavePortfolioChanges {
            get {
                return ResourceManager.GetString("vMsgSavePortfolioChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save changes? ähnelt.
        /// </summary>
        public static string vMsgSavePortfolioChangesTitle {
            get {
                return ResourceManager.GetString("vMsgSavePortfolioChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to load portfolio. ähnelt.
        /// </summary>
        public static string vMsgUnableToLoadPortfolio {
            get {
                return ResourceManager.GetString("vMsgUnableToLoadPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No preview available ähnelt.
        /// </summary>
        public static string vNoPreviewAvailable {
            get {
                return ResourceManager.GetString("vNoPreviewAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        public static string vOrderContextMenuRefresh {
            get {
                return ResourceManager.GetString("vOrderContextMenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Remove ähnelt.
        /// </summary>
        public static string vOrderContextMenuRemove {
            get {
                return ResourceManager.GetString("vOrderContextMenuRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show ähnelt.
        /// </summary>
        public static string vOrderContextMenuShow {
            get {
                return ResourceManager.GetString("vOrderContextMenuShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Order ähnelt.
        /// </summary>
        public static string vPanelOrder {
            get {
                return ResourceManager.GetString("vPanelOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Preview ähnelt.
        /// </summary>
        public static string vPanelPreview {
            get {
                return ResourceManager.GetString("vPanelPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New portfolio ähnelt.
        /// </summary>
        public static string vTitleUnnamedPortfolio {
            get {
                return ResourceManager.GetString("vTitleUnnamedPortfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open active song in editor ähnelt.
        /// </summary>
        public static string vToolbarEditActiveSong {
            get {
                return ResourceManager.GetString("vToolbarEditActiveSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die An unhandled exception occured while running WordsLive. This should not happen. You can try to ignore the exception and continue to work with WordsLive, though this might lead to instabilities. ähnelt.
        /// </summary>
        public static string xUnhandledException {
            get {
                return ResourceManager.GetString("xUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unhandled Exception ähnelt.
        /// </summary>
        public static string xUnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("xUnhandledExceptionTitle", resourceCulture);
            }
        }
    }
}
